//
//  AddFriendRouter.swift
//  BookLover
//
//  Created by Nitesh Chauhan on 6/6/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddFriendRoutingLogic
{
    func navigateToSearchMyFriend()
    func navigateToFilterscene()
    func navigateToUserProfile(withId: String)
}

protocol AddFriendDataPassing
{
    var dataStore: AddFriendDataStore? { get }
}

class AddFriendRouter: NSObject, AddFriendRoutingLogic, AddFriendDataPassing
{
    weak var viewController: AddFriendViewController?
    var dataStore: AddFriendDataStore?
    func navigateToSearchMyFriend() {
        let vcObj = self.viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllerIds.SearchMyFriends) as? SearchMyFriendsViewController
        self.viewController?.navigationController?.pushViewController(vcObj!, animated: true)
    }
    
    func navigateToFilterscene() {
        let vcObj = self.viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllerIds.FilterAge) as? FilterViewController
        let navCon = UINavigationController(rootViewController: vcObj!)
        self.viewController?.present(navCon, animated: true, completion: nil)
    }
    
    func navigateToUserProfile(withId: String) {
        let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllerIds.UserProfile) as! ProfileViewController
        var ds = destinationVC.router?.dataStore
        passDataToProfile(withId: withId, destinationDS: &ds!)
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
    
    func passDataToProfile(withId: String, destinationDS: inout ProfileDataStore)
    {
        destinationDS.userId = withId
        destinationDS.isFromSideMenu = false
    }
}
