//
//  HomeModels.swift
//  BookLover
//
//  Created by ios 7 on 07/05/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//  see http://clean-swift.com
//

import UIKit

enum Home
{
    // MARK: Use cases
    
    struct Request
    {
        struct Favourite {
            var id: String?
            var user_id: String?
            var is_favourite: Bool?
            var atIndex: Int8?
        }
        
        struct Shelf {
            var user_id: String?
            var book_id: String?
            var shelf_status: Int8?
            var is_favourite: Bool?
        }
        
    }
    
    struct Favourite {
        var message : String?
        var error : String?
    }
    
    struct ViewModel
    {
    
        struct PopularBooks {
            
            var total_reviews: Int?
            var id: Int?
            var name: String?
            var isbn_no: String?
            var category_id: Int?
            var author_name: String?
            var pages: Int?
            var description: String?
            var cover_photo: String?
            var publisher_name: String?
            var country: String?
            var is_deleted: Bool?
            var created: String?
            var rating: Double?
            var review_count: Int?
            var reviews: [Reviews]?
            var shelves: [Shelves]?
            
            struct Reviews {
                var book_id: Int?
                var rating: Double?
                var count: Int?
            }
            
            struct Shelves {
                var id: Int?
                var user_id: Int?
                var book_id: Int?
                var shelf_status: Int?
                var is_favourite: Bool?
            }
        }
        
        struct RecentBooks {
            
            var id:Int?
            var name: String?
            var isbn_no: String?
            var category_id: Int?
            var author_name: String?
            var pages: Int?
            var description: String?
            var cover_photo: String?
            var publisher_name: String?
            var country: String?
            var is_deleted: Bool?
            var created: String?
            var rating: Double?
            var review_count: Int?
            var reviews: [Reviews]?
            var shelves: [Shelves]?

            struct Reviews {
               var book_id: Int?
               var rating: Double?
               var count: Int?
            }
            
            struct Shelves {
                var id: Int?
                var user_id: Int?
                var book_id: Int?
                var shelf_status: Int?
                var is_favourite: Bool?
            }
        }
        
        struct Categories {
            
            var id: Int?
            var name: String?
            var description: String?
            var category_image: String?
            var status: Bool?
            var is_deleted: Bool?
        }
        
        var categoriesList : [Categories]?
        var recentBookList : [RecentBooks]?
        var popularBookList : [PopularBooks]?
        var error : String?

    }
    
}
