//
//  HomeWorker.swift
//  BookLover
//
//  Created by ios 7 on 07/05/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class HomeWorker
{
    func hitDashBoardApi(apiResponse:@escaping(responseHandler)) {
        
        if CommonFunctions.sharedInstance.isUserLoggedIn() == true  {
            
            let userId = userDefault.value(forKeyPath: userDefualtKeys.user_Id.rawValue) as! Int16
            
            let param = ["user_id":"\(userId)"]
            let token = Configurator.tokenBearer + (userDefault.value(forKeyPath: userDefualtKeys.user_Token.rawValue) as! String)
            
            let headersArray:HTTPHeaders = ["Content-Type":"application/json","Authorization":token]

            NetworkingWrapper.sharedInstance.connect(urlEndPoint: ApiEndPoints.getDashBoard, httpMethod: .post, headers: headersArray, parameters: param, encoding: nil) { (response) in
                apiResponse(response)
            }

        } else {
            NetworkingWrapper.sharedInstance.connect(urlEndPoint: ApiEndPoints.getDashBoard, httpMethod: .get) { (response) in
                apiResponse(response)
            }
        }
    }
    
    func hitFavouriteUnfavouriteApi(request: [String:Any]?, apiResponse:@escaping(responseHandler)){
        
        let token = Configurator.tokenBearer + (userDefault.value(forKeyPath: userDefualtKeys.user_Token.rawValue) as! String)
        
        let headersArray:HTTPHeaders = ["Content-Type":"application/json","Authorization":token]
        
        NetworkingWrapper.sharedInstance.connect(urlEndPoint: ApiEndPoints.likeDislike, httpMethod: .post, headers: headersArray, parameters:request!, encoding: nil) { (response) in
            apiResponse(response)
        }
    }
    
}
