//
//  SearchBookRouter.swift
//  BookLover
//
//  Created by Mss Mukunda on 22/05/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchBookRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
     func navigateToBookDetail(bookId: String)
}

protocol SearchBookDataPassing
{
  var dataStore: SearchBookDataStore? { get }
}

class SearchBookRouter: NSObject, SearchBookRoutingLogic, SearchBookDataPassing
{
  weak var viewController: SearchBookViewController?
  var dataStore: SearchBookDataStore?
  
    func navigateToBookDetail(bookId: String) {
        let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllerIds.BookDetail) as! BookDetailViewController
        var ds = destinationVC.router?.dataStore
        passDataToBookDetail(bookId: bookId, destinationDS: &ds!)
        pushToBookDetail(source: viewController!, destination: destinationVC)
    }
    
    func pushToBookDetail(source: UIViewController, destination: UIViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    func passDataToBookDetail(bookId: String, destinationDS: inout BookDetailDataStore)
    {
        destinationDS.bookId = bookId
    }
    
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: SearchBookViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: SearchBookDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
