//
//  shelvesWorker.swift
//  BookLover
//
//  Created by Nitesh Chauhan on 6/5/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class shelvesWorker
{
    func getBookShelvesStatus(params: [String:Any]?, apiResponse:@escaping(responseHandler)) {
        
        let token = Configurator.tokenBearer + (userDefault.value(forKeyPath: userDefualtKeys.user_Token.rawValue) as! String)
        let headersArray:HTTPHeaders = ["Content-Type":"application/x-www-form-urlencoded","Authorization": token]
        NetworkingWrapper.sharedInstance.connect(urlEndPoint: ApiEndPoints.getBookShelvesStatus, httpMethod: .post, headers: headersArray, parameters: params, encoding: URLEncoding.default) { (response) in
            apiResponse(response)
        }
    }
}
