//
//  shelvesInteractor.swift
//  BookLover
//
//  Created by Nitesh Chauhan on 6/5/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol shelvesBusinessLogic
{
    func hitShelvesStatusApi(request: shelves.Request)
}

protocol shelvesDataStore
{
    //var name: String { get set }
}

class shelvesInteractor: shelvesBusinessLogic, shelvesDataStore
{
    var presenter: shelvesPresentationLogic?
    var worker: shelvesWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func hitShelvesStatusApi(request: shelves.Request)
    {
        worker = shelvesWorker()
        if CommonFunctions.sharedInstance.isUserLoggedIn() == true {
            let userId = userDefault.value(forKeyPath: userDefualtKeys.user_Id.rawValue) as! Int16
            
            let parameters = [
                "user_id":userId,
                "shelf_status":request.shelf_status
                ] as [String : Any]
            
            worker?.getBookShelvesStatus(params: parameters, apiResponse: { (response) in
                printToConsole(item: response)
                if response.code == SuccessCode {
                    printToConsole(item: request.shelf_status)
                    
                    self.presenter?.presentApiResponse(response: response, shelfStatus: request.shelf_status, IspopUp: request.openPop)
                }
                else {
                    CustomAlertController.sharedInstance.showErrorAlert(error: response.error!)
                    self.presenter?.presenHMsegment()
                }
                
            })
        }
    }
}
