//
//  shelvesRouter.swift
//  BookLover
//
//  Created by Nitesh Chauhan on 6/5/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol shelvesRoutingLogic
{
 func navigateToBookShelves(withData: [String:Any])
    func navigateToAllReview(bookId: String)
    func navigateToBookDetail(bookId: String)
    func navigateToRatingView(bookId: String)
}

protocol shelvesDataPassing
{
  var dataStore: shelvesDataStore? { get }
}

class shelvesRouter: NSObject, shelvesRoutingLogic, shelvesDataPassing
{
  
    
  weak var viewController: shelvesViewController?
  var dataStore: shelvesDataStore?
  
  // MARK: Routing
  
      func navigateToBookShelves(withData: [String : Any]) {
        let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllerIds.BookShelves) as! BookShelvesViewController
        destinationVC.dictShelfData = withData
        destinationVC.callMyBookDismiss = viewController?.performBookPopUpAction()
        let navCountry = UINavigationController(rootViewController: destinationVC)
        self.viewController?.present(navCountry, animated: true, completion: nil)
    }

    func navigateToAllReview(bookId: String) {
        let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllerIds.ShowAllReview) as! ShowAllReviewViewController
        var ds = destinationVC.router?.dataStore
        passDataToAllReview(bookId: bookId, destinationDS: &ds!)
        pushToAllReview(source: viewController!, destination: destinationVC)
    }
    

    func pushToAllReview(source: UIViewController, destination: UIViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    func passDataToAllReview(bookId: String, destinationDS: inout ShowAllReviewDataStore)
    {
        destinationDS.bookId = bookId
    }
    
    func navigateToBookDetail(bookId: String) {
        let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllerIds.BookDetail) as! BookDetailViewController
        var ds = destinationVC.router?.dataStore
        passDataToBookDetail(bookId: bookId, destinationDS: &ds!)
        pushToBookDetail(source: viewController!, destination: destinationVC)
    }
    
    func pushToBookDetail(source: UIViewController, destination: UIViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    func passDataToBookDetail(bookId: String, destinationDS: inout BookDetailDataStore)
    {
        destinationDS.bookId = bookId
    }
    
    func navigateToRatingView(bookId: String) {
        let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllerIds.Rating) as! RatingViewController
        var ds = destinationVC.router?.dataStore
        passDataToRatingView(bookId: bookId, destinationDS: &ds!)
        pushToRatingView(source: viewController!, destination: destinationVC)
    }
    
    func passDataToRatingView(bookId: String, destinationDS: inout RatingDataStore)
    {
        destinationDS.bookId = bookId
        destinationDS.isRatingEdit = false
    }
    
    func pushToRatingView(source: UIViewController, destination: UIViewController) {
        let toRating = UINavigationController(rootViewController: destination)
        source.present(toRating, animated: true, completion: nil)
    }
    
    
  // MARK: Navigation
  
  //func navigateToSomewhere(source: shelvesViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: shelvesDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
