//
//  shelvesModels.swift
//  BookLover
//
//  Created by Nitesh Chauhan on 6/5/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum shelves
{
  // MARK: Use cases
    struct Request
    {
        var shelf_status:Int
        var openPop : Bool
    }
    struct Response
    {
    }
    struct ViewModel
    {
        struct CellData {
            var cover_photo:String?
            var review_count:Int?
            var name: String?
            var author_name: String?
            var rating:Double?
            var is_favourite:Bool
            var id:Int?
            var bookId:Int?
            var shelf_status:Int?
        }
        
        var collectionArray: [CellData]
    }
}
