//
//  ReviewsPrivacyInteractor.swift
//  BookLover
//
//  Created by Mss Mukunda on 14/05/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReviewsPrivacyBusinessLogic
{
  func doSomething(request: ReviewsPrivacy.Something.Request)
}

protocol ReviewsPrivacyDataStore
{
  //var name: String { get set }
}

class ReviewsPrivacyInteractor: ReviewsPrivacyBusinessLogic, ReviewsPrivacyDataStore
{
  var presenter: ReviewsPrivacyPresentationLogic?
  var worker: ReviewsPrivacyWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ReviewsPrivacy.Something.Request)
  {
    worker = ReviewsPrivacyWorker()
    worker?.doSomeWork()
    
    let response = ReviewsPrivacy.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
