//
//  ReviewsPrivacyPresenter.swift
//  BookLover
//
//  Created by Mss Mukunda on 14/05/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReviewsPrivacyPresentationLogic
{
  func presentSomething(response: ReviewsPrivacy.Something.Response)
}

class ReviewsPrivacyPresenter: ReviewsPrivacyPresentationLogic
{
  weak var viewController: ReviewsPrivacyDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ReviewsPrivacy.Something.Response)
  {
  }
}
