//
//  ReviewsPrivacyWorker.swift
//  BookLover
//
//  Created by Mss Mukunda on 14/05/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ReviewsPrivacyWorker
{
  func doSomeWork()
  {
  }
}
