//
//  RegisterRouter.swift
//  BookLover
//
//  Created by ios 7 on 09/05/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RegisterRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func navigateBack()
    func navigateToCompleteProfileScene()
}

protocol RegisterDataPassing
{
  var dataStore: RegisterDataStore? { get }
}

class RegisterRouter: NSObject, RegisterRoutingLogic, RegisterDataPassing
{
  weak var viewController: RegisterViewController?
  var dataStore: RegisterDataStore?

  // MARK: Navigation
  
    func navigateBack() {
        self.viewController?.navigationController?.popViewController(animated: true)
    }
    
    func navigateToCompleteProfileScene() {
        
        let vcObj = self.viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllerIds.CompleteProfile) as? CompleteProfileViewController
        var destinationDS = vcObj?.router!.dataStore!
        passDataToCompleteProfile(source: dataStore!, destination: &destinationDS!, isSetting:false)
        self.viewController?.navigationController?.pushViewController(vcObj!, animated: true)
    }
    
   
    
    func passDataToCompleteProfile(source: RegisterDataStore, destination: inout CompleteProfileDataStore, isSetting: Bool)
    {
        destination.isSetting = isSetting
    }
    
  //func navigateToSomewhere(source: RegisterViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: RegisterDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
