//
//  RegisterWorker.swift
//  BookLover
//
//  Created by ios 7 on 09/05/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class RegisterWorker
{
    func hitSignUpApi(parameters:[String:String], apiResponse:@escaping(responseHandler)) {
        
        NetworkingWrapper.sharedInstance.connect(urlEndPoint: ApiEndPoints.register, httpMethod: .post, parameters: parameters) { (response) in
            apiResponse(response)
        }
    }
}
