//
//  AddCommentRouter.swift
//  BookLover
//
//  Created by Mss Mukunda on 28/05/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddCommentRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)

}

protocol AddCommentDataPassing
{
    var dataStore: AddCommentDataStore? { get }
}

class AddCommentRouter: NSObject, AddCommentRoutingLogic, AddCommentDataPassing
{
    weak var viewController: AddCommentViewController?
    var dataStore: AddCommentDataStore?
    
    
    // MARK: Routing
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: AddCommentViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: AddCommentDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
