//
//  AllNotificationRouter.swift
//  BookLover
//
//  Created by Mss Mukunda on 17/05/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AllNotificationRoutingLogic
{
    func navigateToUserProfile(withId: String)
    func navigateToBookDetail(bookId: Int)
    func navigateToUserReview(reviewId: String)
}

protocol AllNotificationDataPassing
{
  var dataStore: AllNotificationDataStore? { get }
}

class AllNotificationRouter: NSObject, AllNotificationRoutingLogic, AllNotificationDataPassing
{

  weak var viewController: AllNotificationViewController?
  var dataStore: AllNotificationDataStore?
    
    func navigateToUserProfile(withId: String) {
        let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllerIds.UserProfile) as! ProfileViewController
        var ds = destinationVC.router?.dataStore
        passDataToProfile(withId: withId, destinationDS: &ds!)
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
    
    func passDataToProfile(withId: String, destinationDS: inout ProfileDataStore)
    {
        destinationDS.userId = withId
        destinationDS.isFromSideMenu = false
    }
    

    func navigateToBookDetail(bookId: Int) {
        let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllerIds.BookDetail) as! BookDetailViewController
        var ds = destinationVC.router?.dataStore
        passDataToBookDetail(bookId: bookId, destinationDS: &ds!)
        pushToBookDetail(source: viewController!, destination: destinationVC)
    }
    
    func pushToBookDetail(source: UIViewController, destination: UIViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    func passDataToBookDetail(bookId: Int, destinationDS: inout BookDetailDataStore)
    {
        destinationDS.bookId = ("\((bookId))")
    }
    
    
    func navigateToUserReview(reviewId: String) {
        let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllerIds.UserReview) as! UserReviwViewController
        var ds = destinationVC.router?.dataStore
        passDataToUserReview(reviewId: reviewId, destinationDS: &ds!)
        pushToUserReview(source: viewController!, destination: destinationVC)
    }
    
    func pushToUserReview(source: UIViewController, destination: UIViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    func passDataToUserReview(reviewId: String, destinationDS: inout UserReviwDataStore)
    {
        destinationDS.reviewId = reviewId
    }

}
