//
//  LoginModels.swift
//  BookLover
//
//  Created by ios 7 on 08/05/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
  
    struct Request
    {
        var email: String?
        var password: String?
        var token: String?
    }
    
    struct ViewModel
    {
        var error: String?
        var isCompleted : Bool
    }
}
