//
//  LoginPresenter.swift
//  BookLover
//
//  Created by ios 7 on 08/05/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
    func presentLoginResponse(response: ApiResponse)
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
    func presentLoginResponse(response: ApiResponse)
    {
        var viewModel : Login.ViewModel?
        if response.code == SuccessCode {
            let res = response.result as! NSDictionary
            let isComplete = (res["is_complete"] as! Bool) == true ? true : false
            
            viewModel = Login.ViewModel(
                error: nil,
                isCompleted: isComplete)
            userDefault.set(isComplete, forKey: userDefualtKeys.userProfileCompleted.rawValue)
        } else {
            viewModel = Login.ViewModel(error: response.error, isCompleted: false)
        }
        viewController?.displayLoginResponse(viewModel: viewModel!)
    }
  
}
