//
//  LoginWorker.swift
//  BookLover
//
//  Created by ios 7 on 08/05/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias fbLoginHandler = ((_ response: String?, _ error: Error?) -> (Void))


class LoginWorker
{
    func hitLoginApi(parameters:[String:String], apiResponse:@escaping(responseHandler)) {
        NetworkingWrapper.sharedInstance.connect(urlEndPoint: ApiEndPoints.login, httpMethod: .post, parameters: parameters) { (response) in
            apiResponse(response)
        }
    }
}
