//
//  LoginRouter.swift
//  BookLover
//
//  Created by ios 7 on 08/05/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func navigateToRegisterScene()
    func navigateToForgotPassword()
    func navigateToCompleteProfileScene()
}

protocol LoginDataPassing
{
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
    
    
  weak var viewController: LoginViewController?
  var dataStore: LoginDataStore?
  
  // MARK: Navigation
  
    func navigateToRegisterScene() {
        let vcObj = self.viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllerIds.Register) as? RegisterViewController
        self.viewController?.navigationController?.pushViewController(vcObj!, animated: true)
    }
    
    
    func navigateToForgotPassword() {
        let vcObj = self.viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllerIds.ForgotPasword) as? ForgotPasswordViewController
        self.viewController?.navigationController?.pushViewController(vcObj!, animated: true)
    }

    
    func navigateToCompleteProfileScene() {
        
        let vcObj = self.viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllerIds.CompleteProfile) as? CompleteProfileViewController
        var destinationDS = vcObj?.router!.dataStore!
        passDataToShowOrder(source: dataStore!, destination: &destinationDS!, isSetting:false)
        self.viewController?.navigationController?.pushViewController(vcObj!, animated: true)
    }
    
   
    func passDataToShowOrder(source: LoginDataStore, destination: inout CompleteProfileDataStore, isSetting: Bool)
    {
        destination.isSetting = isSetting
    }
 
}
