//
//  SearchMyFriendsRouter.swift
//  BookLover
//
//  Created by Mss Mukunda on 07/06/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchMyFriendsRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
     func navigateToUserProfile(withId: String) 
}

protocol SearchMyFriendsDataPassing
{
  var dataStore: SearchMyFriendsDataStore? { get }
}

class SearchMyFriendsRouter: NSObject, SearchMyFriendsRoutingLogic, SearchMyFriendsDataPassing
{
  weak var viewController: SearchMyFriendsViewController?
  var dataStore: SearchMyFriendsDataStore?
  
    func navigateToUserProfile(withId: String) {
        let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllerIds.UserProfile) as! ProfileViewController
        var ds = destinationVC.router?.dataStore
        passDataToProfile(withId: withId, destinationDS: &ds!)
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
    
    func passDataToProfile(withId: String, destinationDS: inout ProfileDataStore)
    {
        destinationDS.userId = withId
        destinationDS.isFromSideMenu = false
    }
}
