//
//  BookDetailWorker.swift
//  BookLover
//
//  Created by ios 7 on 28/05/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class BookDetailWorker
{

    func hitBookDetailApi(bookId: String,apiResponse:@escaping(responseHandler)) {
        
        var endUrl: String?
        if CommonFunctions.sharedInstance.isUserLoggedIn() == true {
            endUrl = ApiEndPoints.bookDetail + "\(bookId)/" + CommonFunctions.sharedInstance.getUserId() + ".json"
        } else{
            endUrl = ApiEndPoints.bookDetail + bookId + ".json"
        }
        NetworkingWrapper.sharedInstance.connect(urlEndPoint: endUrl!, httpMethod: .get) { (response) in
            apiResponse(response)
        }
    }
    
}
