//
//  BookDetailModels.swift
//  BookLover
//
//  Created by ios 7 on 28/05/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//  see http://clean-swift.com
//

import UIKit

enum BookDetail
{
  // MARK: Use cases
    struct Request
    {
        struct FavUnfavorite{
            var status : Bool?
            var shelveId : String?
        }
    }
    struct Response
    {
       
    }
    struct ViewModel
    {
        struct FavUnfavorite{
            var success : String?
            var error : String?
        }
        
        struct Review {
            
            var is_Like: Bool?
            var  book_id : Int16?
            var  commentCount : Int?
            var  created_at : String?
            var  description : String?
            var  id : Int16?
            var  is_deleted : Bool?
            var  likeCount : Int?
            var  rating : Double?
            var  status : Bool?
            var  updated_at : String?
            var  user : ProfileInfo.Data?
            
//            struct UserInfo {
//
//                var  about : String?
//                var  active : Bool?
//                var  address : String?
//                var  age : String?
//                var  city : String?
//                var  country : String?
//                var  created_at : String?
//                var  dob : String?
//                var  email : String?
//                var  firstname : String?
//                var  gender : String?
//                var  group_id : String?
//                var  id : Int16?
//                var  is_deleted : Bool?
//                var  is_logged_in : Bool?
//                var  last_seen : String?
//                var  lastname : String?
//                var  lat : Float32?
//                var  lng : Float32?
//                var  message_privacy : Bool?
//                var  modified_at : String?
//                var  otp : Int16?
//                var  profile_privacy : Bool?
//                var  review_privacy : Bool?
//                var  role_id : Int16?
//                var  social_token : Int16?
//                var  social_type : String?
//                var  state : String?
//                var  status : Bool?
//                var  updated_at : String?
//                var  user_image : String?
//                var  zipcode : Int16?
//                var  privacies : [Privacies]?
//
//                struct Privacies {
//
//                    var id: Int?
//                    var user_id: Int?
//                    var profile_pic: Int?
//                    var email: Int?
//                    var age: Int?
//                    var gender: Int?
//                    var follow: Int?
//                    var comment: Int?
//                    var message: Int?
//                }
//            }
        }
        
        struct Books {
            
            var id: Int?
            var name: String?
            var isbn_no: String?
            var category_id: Int?
            var author_name: String?
            var pages: Int?
            var description: String?
            var cover_photo: String?
            var publisher_name: String?
            var country: String?
            var is_deleted: Bool?
            var created: String?
            var rating: Double?
            var review_count: Int?
            var shelves: [Shelves]?
            var category: Category?
            
            struct Shelves {
                var id: Int?
                var user_id: Int?
                var book_id: Int?
                var shelf_status: Int?
                var is_favourite: Bool?
            }
            
            struct Category {
                var id: Int?
                var name: String?
                var description: String?
                var category_image: String?
                var status: Int?
                var is_deleted: Bool?
            }
        }
        
        struct User_Review {
            
            var id: Int?
            var user_id: Int?
            var book_id: Int?
            var description: String?
            var rating: Double?
            var status: Int?
            var is_deleted: Bool?
            var created_at: String?
            var updated_at: String?
            var likeCount: Int?
            var commentCount: Int?
            var is_like : Bool?
            
        }
        
        var books: Books?
        var reviewList : [Review]?
        var userReview: User_Review?
        var error: String?
    }
}


