//
//  CompleteProfileRouter.swift
//  BookLover
//
//  Created by ios 7 on 10/05/18.
//  Copyright (c) 2018 iOS Team. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CompleteProfileRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func navigateBack()
    func navigateToStateScene(withData: [CompleteProfile.ViewModel.StateData])
    func navigateToCountryScene()
}

protocol CompleteProfileDataPassing
{
  var dataStore: CompleteProfileDataStore? { get }
}

class CompleteProfileRouter: NSObject, CompleteProfileRoutingLogic, CompleteProfileDataPassing
{
  weak var viewController: CompleteProfileViewController?
  var dataStore: CompleteProfileDataStore?
  

  // MARK: Navigation
  
    func navigateBack() {
        self.viewController?.navigationController?.popViewController(animated: true)
    }
    
    func navigateToStateScene(withData: [CompleteProfile.ViewModel.StateData]) {
        
        let vcObj = self.viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllerIds.State) as? StateViewController
        vcObj?.arrStateList = withData
        vcObj?.callbackDismiss = viewController?.presenterStateDismisedAction()
        let navState = UINavigationController(rootViewController: vcObj!)
        self.viewController?.present(navState, animated: true, completion: nil)
    }

    func navigateToCountryScene() {
        
        let vcObj = self.viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllerIds.Country) as? CountryViewController
        vcObj?.callbackDismiss = viewController?.presenterCountryDismisedAction()
        let navCountry = UINavigationController(rootViewController: vcObj!)
        self.viewController?.present(navCountry, animated: true, completion: nil)
    }
}
