//
//  ChatRouter.swift
//  WebSocket
//
//  Created by Mss Mukunda on 25/06/18.
//  Copyright (c) 2018 Mss Mukunda. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ChatRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func navigateToUserProfile(withId: String)
}

protocol ChatDataPassing
{
  var dataStore: ChatDataStore? { get }
}

class ChatRouter: NSObject, ChatRoutingLogic, ChatDataPassing
{
  weak var viewController: ChatViewController?
  var dataStore: ChatDataStore?
    
    func navigateToUserProfile(withId: String) {
        let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: ViewControllerIds.UserProfile) as! ProfileViewController
        var ds = destinationVC.router?.dataStore
        passDataToProfile(withId: withId, destinationDS: &ds!)
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
    
    func passDataToProfile(withId: String, destinationDS: inout ProfileDataStore)
    {
        destinationDS.userId = withId
        destinationDS.isFromSideMenu = false
    }
  
  
}
